name: My Script Work flow
on: push
jobs:
    script_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: list file
          run: ls -ltra
        - name: Execute shell script
          run: |
            chmod 755 script.sh
            ./script.sh
            echo "action_state=yellow" >> $GITHUB_ENV
            echo "Dispalying env"
            cat $GITHUB_ENV
            echo "Displaying the env variable"
            echo ${{env.action_state}}