name: My Script Work flow
on: push
jobs:
    script_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: list file
          run: ls -ltra
        - name: Execute shell script
          run: |
            #chmod 755 script.sh
            #./script.sh
            # echo "action_state=yellow" >> $GITHUB_ENV
            #echo "Dispalying env"
            #cat $GITHUB_ENV
            #echo "Displaying the env variable"
            #echo ${{env.action_state}}>> variable.txt
            #cat variable.txt
            wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64.tar.gz
            tar -zxvf yq_linux_amd64.tar.gz
            yq --version
            ls -ltr $GITHUB_WORKSPACE
            ENV_FILE= $GITHUB_WORKSPACE/conf/dev.yaml
            echo $ENV_FILE
            name= $(./yq_linux_amd64 e .name ${{env.ENV_FILE}})
            echo $name