name: My second Work flow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Multiple Command example
          run: |
            echo "My 1st github actions job"
            ls -altr
            cat README.md

#        - name: List files
#          run: ls -ltr
#        - name: Read file
#          run: cat README.md
