# Step leven env variables

name: Explore variables and secrets at step level
on:
    push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: sambit2016
        IMAGE_NAME: github-actions-nginx
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    - name: Docker login
      env:
        DOCKER_PASSWORD: xxxxxxxxxxx
        DOCKER_USERNAME: sambit2016
      run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}

    - name: Docker publish
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: sambit2016
        IMAGE_NAME: github-actions-nginx
      run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest