# workflow leven env variables

name: Explore variables and secrets at workflow level
on:
    push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: sambit2016
    IMAGE_NAME: github-actions-nginx
jobs:
  docker:      
    runs-on: ubuntu-latest
    steps:
    - name: Docker build     
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    - name: Docker login
      env:
        DOCKER_PASSWORD: XXXXXXXXXX
      run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}

    - name: Docker publish
      run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
